# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: testvariable
- name: dockerId
  value: 'mydevopstest'
- name: imageName
  value: 'imagenametest'

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world! $(urlkien)
  displayName: 'Run a one-line script'
- script: |
    docker build -t $(dockerId)/$(imageName):$(build.buildid) .
  displayName: 'build image'

- task: Delay@1
  inputs:
    delayForMinutes: '2' 

- script: docker run -d -p 5000:5000 $(dockerId)/$(imageName):$(build.buildid)
  displayname: 'run test app'

- task: Delay@1
  inputs:
    delayForMinutes: '2' 
    
- script: curl localhost:5000
  displayname: 'test app live'
  
