
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline



variables:
- group: testvariable
- name: dockerId
  value: 'mydevopstest'
- name: imageName
  value: 'imagenametest'

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'
  
- script: npm install -g sonarqube-scanner
  displayName: 'Run a one-line script'

steps:
- script: sonar-scanner -Dsonar.projectKey=testpython -Dsonar.sources=.  -Dsonar.host.url=http://13.67.39.98:9000  -Dsonar.login=bb5905c40b44eca1d95c96a09d03fbeb9bb8b558
  displayName: 'Run a one-line script'

- task: SonarQubePostTest@1

- script: echo Hello, world! $(urlkien)
  displayName: 'Run a one-line script'
- script: |
    docker build -t $(dockerId)/$(imageName):$(build.buildid) .
  displayName: 'build image'



- script: docker run -d -p 5000:5000 $(dockerId)/$(imageName):$(build.buildid)
  displayName: 'run test app'

- script: sleep 5
  displayName: 'run wait'
    
- script: curl localhost:5000
  displayName: 'test app live'
  
